routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/****************** Route for front-end **********************/
Route::get('/products','ProductController@getAllProducts')->name('product-list');       //defined in cafe menu
Route::get('/products/featured','ProductController@getAllFeaturedProducts')->name('featured-products');
Route::get('/product/{slug}','ProductController@show')->name('product-detail');    //define in product-list   product's title
Route::get('/category/{slug}','CategoryController@getAllProductsByCategory')->name('category-products');    //defined in Helpers.php
Route::get('/category/{parent_slug}/{slug}','CategoryController@getAllProductsByChildCategory')->name('child-category-products');
Route::post('/product/{slug}','ProductController@submitReview')->name('product-review');
Route::get('/cart','CartController@showCart')->name('cart-list');
Route::get('/checkout','CartController@checkout')->name('checkout')->middleware(['auth','user']);
//route for cart
Route::post('/cart/add','CartController@addToCart')->name('add-to-cart');
Route::get('/loadmore', 'LoadMoreController@index');
Route::post('/loadmore/load_data', 'LoadMoreController@load_data')->name('loadmore.load_data');
Route::get('/esewa','CartController@esewa')->name('esewa');


/****************** Route for front-end **********************/



/****************** Route for user redirect on their dashboard **********************/

Route::group(['prefix'=>'admin','middleware'=>['auth','admin']],function (){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('slider','SliderController');
    Route::resource('category','CategoryController');
    Route::resource('product','ProductController');
    Route::resource('message','MessageController');
    Route::resource('user','UserController');
    Route::get('/change-pwd/{id}','UserController@changePassword')->name('user-change-pwd');
    Route::put('/change-pwd/{id}','UserController@submitChangePassword')->name('password-change');
});

//for show sub-category in the product-form
Route::post('/get-child','CategoryController@getChildByParent')->name('get-child')->middleware('auth');
//


Route::group(['prefix'=>'seller','middleware'=>['auth','seller']],function (){
    Route::get('/','HomeController@seller')->name('seller');

    Route::resource('products','SellerProductController');
});

Route::group(['prefix'=>'user','middleware'=>['auth','user']],function (){
    Route::get('/','HomeController@user')->name('user');
});

/****************** Route for user redirect on their dashboard **********************/






//Auth route for login and register

Route::get('/', 'FrontendController@index')->name('homepage');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Auth route for login and register

resources/views/admin/category-form.blade.php
@extends('layouts.admin')

@section('scripts')

    <script>
        $('#is_parent').change(function () {
            let is_checked = $(this).prop('checked');
            if(is_checked){
                $('#parent_id').val("");
                $('#parent_div').addClass('d-none');
            }else{
                $('#parent_div').removeClass('d-none');
            }
        });
    </script>

@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">Category {{ isset($category_data) ? 'Update' : 'Add' }} Form</div>
                    <div class="ibox-tools">

                    </div>
                </div>
                <div class="ibox-body">

                    @if(isset($category_data))
                        {{ Form::open(['url'=>route('category.update', $category_data->id),'class'=>'form','files'=>true]) }}
                        @method('put')
                    @else
                        {{ Form::open(['url'=>route('category.store'),'class'=>'form','files'=>true]) }}
                    @endif

                    <div class="form-group row">
                        {{ Form::label('title','Title',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::text('title',@$category_data->title,['class'=>'form-control form-control-sm','required'=>true,'id'=>'title','placeholder'=>'Enter title']) }}
                            @error('title')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                        <div class="form-group row">
                            {{ Form::label('is_parent','Is Parent ?',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::checkbox('is_parent','1',isset($category_data, $category_data->parent_id) && $category_data->parent_id != null ? false : true,['id'=>'is_parent']) }} Yes
                            </div>
                        </div>


                        <div class="form-group row {{ isset($category_data, $category_data->parent_id) && $category_data->parent_id != null ? '' : 'd-none' }}" id="parent_div">
                            {{ Form::label('parent_id','Parent Category',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::select('parent_id',@$parent_data,@$category_data->parent_id,['class'=>'form-control form-control-sm','placeholder'=>'---Select any one---']) }}
                                @error('parent_id')
                                <span class="span-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>


                    <div class="form-group row">
                        {{ Form::label('status','Status',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::select('status',['active'=>'Active','inactive'=>'Inactive'],@$category_data->status,['class'=>'form-control form-control-sm','required'=>true]) }}
                            @error('status')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>


                        <div class="form-group row">
                            {{ Form::label('image','Image',['class'=>'col-sm-3']) }}
                            <div class="col-sm-4">
                                {{ Form::file('image',['id'=>'image','accept'=>'image/*']) }}
                                @error('image')
                                <span class="span-danger">{{ $message }}</span>
                                @enderror
                            </div>

                        <div class="col-sm-4">
                            @if(isset($category_data))

                                <img src="{{ imageUrl($category_data->image, 'category') }}" alt="" style="max-width: 100px;" class="img img-fluid img-thumbnail">

                            @endif
                        </div>

                    </div>

                    <div class="form-group row">
                        <div class="col-sm-9 offset-sm-3">
                            {{ Form::button('<i class="fa fa-trash"></i> Re-set',['class'=>'btn btn-danger btn-sm','id'=>'reset','type'=>'reset']) }}
                            {{ Form::button('<i class="fa fa-paper-plane"></i> Submit',['class'=>'btn btn-success btn-sm','id'=>'submit','type'=>'submit']) }}
                        </div>
                    </div>



                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/category-list.blade.php
@extends('layouts.admin')

@section('scripts')
    <script>
        $('.delete_btn').click(function (e) {
            var id= $(this).data('id');
            var confirmed = confirm('Are you sure you want to delete the category data ?');
            if(confirmed){
                $('#'+id).submit();
            }
        });
    </script>

@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">Category List</div>
                    <div class="ibox-tools">
                        <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                        <a class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-ellipsis-v"></i></a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item">option 1</a>
                            <a class="dropdown-item">option 2</a>
                        </div>
                    </div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover">
                        <thead>
                        <th>Title</th>
                        <th>Sub Category</th>
                        <th>Image</th>
                        <th>Status</th>
                        <th>Action</th>
                        </thead>
                        <tbody>
                        @if($category_data)

                            @foreach($category_data as $category_info)

                                <tr>
                                    <td>{{ $category_info->title }}</td>

                                    <td>
                                        @foreach($category_info->child_cats as  $child_category)
                                            <div class="row border-bottom">
                                                <div class="col-sm-6">
                                                    <a href="{{ route('category.edit',$child_category->id) }}" class="btn btn-link">
                                                        {{ $child_category->title }}
                                                    </a>
                                                </div>

                                                <div class="col-sm-6">
                                                    {{ Form::open(['url'=>route('category.destroy', $child_category->id),'onsubmit'=>'return confirm("Are you sure you want to delete this category.")']) }}
                                                    @method('delete')
                                                    {{ Form::button("<i class='fa fa-trash'></i>",['type'=>'submit','class'=>'btn btn-light btn-sm float-auto','style'=>'color:red;']) }}
                                                    {{ Form::close() }}
                                                </div>
                                            </div>
                                        @endforeach
                                    </td>

                                    <td>
                                        <img src="{{ imageUrl($category_info->image, 'category') }}" alt="" style="max-width: 100px;" class="img img-fluid img-thumbnail">
                                    </td>


                                    <td>
                                            <span class="badge badge-{{ $category_info->status == 'active' ? 'success' : 'danger' }}">
                                                {{ ucfirst($category_info->status) }}
                                            </span>
                                    </td>

                                    <td>
                                        <a href="{{ route('category.edit', $category_info->id) }}" class="btn btn-success btn-sm">
                                            <i class="fa fa-edit"></i>
                                        </a>


                                        <a href="javascript:;" class="btn btn-danger btn-sm delete_btn" data-id="category-{{ $category_info->id }}">
                                            <i class="fa fa-trash"></i>
                                        </a>

                                        {{ Form::open(['url'=>route('category.destroy', $category_info->id), 'id'=>'category-'.$category_info->id]) }}
                                        @method('delete')
                                        {{ Form::close() }}



                                    </td>

                                </tr>

                            @endforeach

                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/change-pwd.blade.php
@extends('layouts.admin')

@section('scripts')

@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">User {{ isset($user_data) ? 'Update' : 'Add' }} Form</div>
                    <div class="ibox-tools">

                    </div>
                </div>
                <div class="ibox-body">

                        {{ Form::open(['url'=>route('password-change', $user_data->id),'class'=>'form','files'=>true]) }}
                        @method('put')

                        <div class="form-group row">
                            {{ Form::label('password','Password',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::password('password',['class'=>'form-control form-control-sm','required'=>true,'id'=>'password','placeholder'=>'Enter password']) }}
                                @error('password')
                                <span class="span-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('password_confirmation','Re-Password',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::password('password_confirmation',['class'=>'form-control form-control-sm','required'=>true,'id'=>'password_confirmation','placeholder'=>'Enter password_confirmation']) }}
                            </div>
                        </div>


                    <div class="form-group row">
                        <div class="col-sm-9 offset-sm-3">
                            {{ Form::button('<i class="fa fa-trash"></i> Re-set',['class'=>'btn btn-danger btn-sm','id'=>'reset','type'=>'reset']) }}
                            {{ Form::button('<i class="fa fa-paper-plane"></i> Submit',['class'=>'btn btn-success btn-sm','id'=>'submit','type'=>'submit']) }}
                        </div>
                    </div>



                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/product-form.blade.php
@extends('layouts.admin')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/summernote-bs4.css') }}">
@endsection

@section('scripts')
    <script src="{{ asset('js/summernote-bs4.js') }}"></script>

    {{-- for summer-note --}}
    <script>
        $('#description').summernote({
            height:150
        });

        {{-- for show sub-category in the product-form --}}
        $('#cat_id').change(function () {
           var cat_id = $('#cat_id').val();
           var sub_cat_id = "{{ (isset($product_data)) ? $product_data->sub_cat_id : null }}";
            if(cat_id){
                $.ajax({
                    url: "{{ route('get-child') }}",
                    type: "post",
                    data: {
                        _token: "{{ csrf_token() }}",
                        cat_id: cat_id
                    },
                    success:function (response) {
                        if(typeof(response) != 'object'){
                            response = JSON.parse(response);
                        }

                        var html_option = "<option value='' selected > -- Select Any One -- </option>";
                        if(response.status){
                            $.each(response.data, function (key,value) {
                                html_option += "<option value='"+value.id+"' ";

                                if(value.id == sub_cat_id){
                                    html_option += 'selected';
                                }
                                html_option += " > "+value.title+" </option>";
                            });
                            $('#sub_cat_div').removeClass('d-none');
                        }else{
                            $('#sub_cat_div').addClass('d-none');
                        }

                        $('#sub_cat_id').html(html_option);

                    }
                });
            }
        });

        $('#cat_id').change();
    </script>

@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">Product {{ isset($product_data) ? 'Update' : 'Add' }} Form</div>
                    <div class="ibox-tools">

                    </div>
                </div>
                <div class="ibox-body">

                    @if(isset($product_data))
                        {{ Form::open(['url'=>route('product.update', $product_data->id),'class'=>'form','files'=>true]) }}
                        @method('put')
                    @else
                        {{ Form::open(['url'=>route('product.store'),'class'=>'form','files'=>true]) }}
                    @endif

                    <div class="form-group row">
                        {{ Form::label('title','Title',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::text('title',@$product_data->title,['class'=>'form-control form-control-sm','required'=>true,'id'=>'title','placeholder'=>'Enter title']) }}
                            @error('title')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('summary','Summary',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::textarea('summary',@$product_data->summary,['class'=>'form-control form-control-sm','required'=>true,'id'=>'summary','placeholder'=>'Enter summary','rows'=>5,'style'=>'resize:none']) }}
                            @error('summary')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('description','Description',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::textarea('description',@$product_data->description,['class'=>'form-control form-control-sm','required'=>false,'id'=>'description','placeholder'=>'Enter description','rows'=>5,'style'=>'resize:none']) }}
                            @error('description')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row">
                        {{ Form::label('cat_id','Category',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::select('cat_id',$parent_data,@$product_data->cat_id,['class'=>'form-control form-control-sm','required'=>true,'id'=>'cat_id','placeholder'=>'---Select any one---']) }}
                            @error('cat_id')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row d-none " id="sub_cat_div">
                        {{ Form::label('sub_cat_id','Sub-Category',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::select('sub_cat_id',$parent_data,@$product_data->sub_cat_id,['class'=>'form-control form-control-sm','id'=>'sub_cat_id','placeholder'=>'---Select any one---']) }}
                            @error('sub_cat_id')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('price','Price(NPR. )',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::text('price',@$product_data->price,['class'=>'form-control form-control-sm','required'=>true,'id'=>'price','placeholder'=>'Enter price','min'=>0]) }}
                            @error('price')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('discount','Discount(% )',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::text('discount',@$product_data->discount,['class'=>'form-control form-control-sm','required'=>false,'id'=>'discount','placeholder'=>'Enter discount','min'=>0,'max'=>100]) }}
                            @error('discount')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('delivery_charge','Delivery Charge',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::text('delivery_charge',@$product_data->delivery_charge,['class'=>'form-control form-control-sm','required'=>true,'id'=>'delivery_charge','placeholder'=>'Enter delivery_charge']) }}
                            @error('delivery_charge')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row">
                        {{ Form::label('is_featured','Day of The Item ?',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::checkbox('is_featured','1',isset($product_data, $product_data->is_featured) && $product_data->is_featured != null ? false : true,['id'=>'is_featured']) }}
                        
                        </div>
                    </div>


                    <div class="form-group row">
                        {{ Form::label('status','Status',['class'=>'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::select('status',['active'=>'Active','inactive'=>'Inactive'],@$product_data->status,['class'=>'form-control form-control-sm','required'=>true]) }}
                            @error('status')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row">
                        {{ Form::label('image','Image',['class'=>'col-sm-3']) }}
                        <div class="col-sm-4">
                            {{ Form::file('image',['id'=>'image','accept'=>'image/*','required'=>(isset($product_data) ? false : true)]) }}
                            @error('image')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="col-sm-4">
                            @if(isset($product_data))
                                <img src="{{ imageUrl($product_data->image, 'product') }}" alt=""
                                     style="max-width: 100px;" class="img img-fluid img-thumbnail">
                            @endif
                        </div>

                    </div>


                    <div class="form-group row">
                        {{ Form::label('related_image','Related_Image',['class'=>'col-sm-3']) }}
                        <div class="col-sm-4">
                            {{ Form::file('rel_image[]',['accept'=>'image/*','multiple'=>true]) }}
                            @error('related_image')
                            <span class="span-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                        {{-- for related image --}}
                        @if(isset($product_data->images))

                            <div class="form-group row">
                                @foreach($product_data->images as $rel_image)
                                    <div class="col-sm-3">
                                        <img src="{{ asset('uploads/product/Thumb-'.$rel_image->image_name) }}" alt="" class="img img-fluid img-thumbnail">
                                        {{ Form:: checkbox('del_image[]',$rel_image->image_name, false) }} Delete
                                    </div>
                                @endforeach
                            </div>

                        @endif


                    <div class="form-group row">
                        <div class="col-sm-9 offset-sm-3">
                            {{ Form::button('<i class="fa fa-trash"></i> Re-set',['class'=>'btn btn-danger btn-sm','id'=>'reset','type'=>'reset']) }}
                            {{ Form::button('<i class="fa fa-paper-plane"></i> Submit',['class'=>'btn btn-success btn-sm','id'=>'submit','type'=>'submit']) }}
                        </div>
                    </div>


                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/product-list.blade.php
@extends('layouts.admin')

@section('scripts')
    <script>
        $('.delete_btn').click(function (e) {
            var id= $(this).data('id');
            var confirmed = confirm('Are you sure you want to delete the product data ?');
            if(confirmed){
                $('#'+id).submit();
            }
        });
    </script>

@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">Product List</div>
                    <div class="ibox-tools">
                        <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                        <a class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-ellipsis-v"></i></a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item">option 1</a>
                            <a class="dropdown-item">option 2</a>
                        </div>
                    </div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover">
                        <thead>
                        <th>Title</th>
                        <th>Category</th>
                        <th>Price</th>
                        <th>Is Featured</th>
                        <th>Seller</th>
                        <th>Image</th>
                        <th>Status</th>
                        <th>Action</th>
                        </thead>
                        <tbody>
                        @if($product_data)

                            @foreach($product_data as $product_info)

                                <tr>
                                    <td>{{ $product_info->title }}</td>

                                    <td>
                                        {{ $product_info->cat_info['title'] }}
                                        <sub>
                                            {{ $product_info->sub_cat_info['title']}}
                                        </sub>
                                    </td>

                                    <td> NPR. {{ number_format($product_info->actual_cost) }} </td>

                                    <td> {{ ($product_info->is_featured == 1 ) ? 'Yes' : 'No' }} </td>

                                    <td>{{ $product_info->seller_info['name'] }}</td>

                                    <td>
                                        <img src="{{ imageUrl($product_info->image, 'product') }}" alt="" style="max-width: 100px;" class="img img-fluid img-thumbnail">
                                    </td>


                                    <td>
                                            <span class="badge badge-{{ $product_info->status == 'active' ? 'success' : 'danger' }}">
                                                {{ ucfirst($product_info->status) }}
                                            </span>
                                    </td>

                                    <td>
                                        <a href="{{ route('product.edit', $product_info->id) }}" class="btn btn-success btn-sm">
                                            <i class="fa fa-edit"></i>
                                        </a>


                                        <a href="javascript:;" class="btn btn-danger btn-sm delete_btn" data-id="product-{{ $product_info->id }}">
                                            <i class="fa fa-trash"></i>
                                        </a>

                                        {{ Form::open(['url'=>route('product.destroy', $product_info->id), 'id'=>'product-'.$product_info->id]) }}
                                        @method('delete')
                                        {{ Form::close() }}



                                    </td>

                                </tr>

                            @endforeach

                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


@endsection