routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/****************** Route for front-end **********************/
Route::get('/products','ProductController@getAllProducts')->name('product-list');       //defined in cafe menu
Route::get('/products/featured','ProductController@getAllFeaturedProducts')->name('featured-products');
Route::get('/product/{slug}','ProductController@show')->name('product-detail');    //define in product-list   product's title
Route::get('/category/{slug}','CategoryController@getAllProductsByCategory')->name('category-products');    //defined in Helpers.php
Route::get('/category/{parent_slug}/{slug}','CategoryController@getAllProductsByChildCategory')->name('child-category-products');
Route::post('/product/{slug}','ProductController@submitReview')->name('product-review');
Route::get('/cart','CartController@showCart')->name('cart-list');
Route::get('/checkout','CartController@checkout')->name('checkout')->middleware(['auth','user']);
//route for cart
Route::post('/cart/add','CartController@addToCart')->name('add-to-cart');
Route::get('/loadmore', 'LoadMoreController@index');
Route::post('/loadmore/load_data', 'LoadMoreController@load_data')->name('loadmore.load_data');
Route::get('/esewa','CartController@esewa')->name('esewa');


/****************** Route for front-end **********************/



/****************** Route for user redirect on their dashboard **********************/

Route::group(['prefix'=>'admin','middleware'=>['auth','admin']],function (){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('slider','SliderController');
    Route::resource('category','CategoryController');
    Route::resource('product','ProductController');
    Route::resource('message','MessageController');
    Route::resource('user','UserController');
    Route::get('/change-pwd/{id}','UserController@changePassword')->name('user-change-pwd');
    Route::put('/change-pwd/{id}','UserController@submitChangePassword')->name('password-change');
});

//for show sub-category in the product-form
Route::post('/get-child','CategoryController@getChildByParent')->name('get-child')->middleware('auth');
//


Route::group(['prefix'=>'seller','middleware'=>['auth','seller']],function (){
    Route::get('/','HomeController@seller')->name('seller');

    Route::resource('products','SellerProductController');
});

Route::group(['prefix'=>'user','middleware'=>['auth','user']],function (){
    Route::get('/','HomeController@user')->name('user');
});

/****************** Route for user redirect on their dashboard **********************/






//Auth route for login and register

Route::get('/', 'FrontendController@index')->name('homepage');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Auth route for login and register

resources/views/admin/section/footer.blade.php
<!-- BEGIN PAGA BACKDROPS-->
<div class="sidenav-backdrop backdrop"></div>
<div class="preloader-backdrop">
    <div class="page-preloader">Loading</div>
</div>
<!-- END PAGA BACKDROPS-->
<script src="{{ asset('js/manifest.js') }}"></script>
<script src="{{ asset('js/vendor.js') }}"></script>
<script src="{{ asset('js/admin.js') }}"></script>
@yield('scripts')

</body>

</html>

resources/views/admin/section/header.blade.php
<header class="header">
    <div class="page-brand">
        <a class="link" href="{{ route(auth()->user()->role) }}">
                    <span class="brand">
                        Admin CMS
                    </span>
            <span class="brand-mini">
                <i class="fa fa-home"></i>
            </span>
        </a>

    </div>
    <div class="flexbox flex-1">
        <!-- START TOP-LEFT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li>
                <a class="nav-link sidebar-toggler js-sidebar-toggler"><i class="ti-menu"></i></a>
            </li>

        </ul>
        <!-- END TOP-LEFT TOOLBAR-->
        <!-- START TOP-RIGHT TOOLBAR-->
        <ul class="nav navbar-toolbar">

            <li class="dropdown dropdown-user">
                <a class="nav-link dropdown-toggle link" data-toggle="dropdown">
                    <i class="fa fa-user"></i> &nbsp;
                    {{ auth()->user()->name }}
                    <i class="fa fa-angle-down m-l-5"></i></a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="profile.html"><i class="fa fa-user"></i>Profile</a>
                    <a class="dropdown-item" href="{{ route('user-change-pwd',auth()->user()->id) }}"><i class="fa fa-key"></i>Change Password</a>
                    <li class="dropdown-divider"></li>

                    <a class="dropdown-item" href="javascript:;" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        <i class="fa fa-power-off"></i>Logout
                    </a>

                    {{ Form::open(['url'=>route('logout'), 'id'=>'logout-form']) }}
                    {{ Form::close() }}

                </ul>
            </li>
        </ul>
        <!-- END TOP-RIGHT TOOLBAR-->
    </div>
</header>

resources/views/admin/section/notify.blade.php
@if(session('success'))
    <div class="alert alert-success alert-bordered alert-dismissable fade show">
        <button class="close" data-dismiss="alert" aria-label="Close">x</button>
        {{ session('success') }}
    </div>
@endif


@if(session('error'))
    <div class="alert alert-danger alert-bordered alert-dismissable fade show">
        <button class="close" data-dismiss="alert" aria-label="Close">x</button>
        {{ session('error') }}
    </div>
@endif


@if(session('warning'))
    <div class="alert alert-warning alert-bordered alert-dismissable fade show">
        <button class="close" data-dismiss="alert" aria-label="Close">x</button>
        {{ session('warning') }}
    </div>
@endif

resources/views/admin/section/sidebar.blade.php
<!-- START SIDEBAR-->
<nav class="page-sidebar" id="sidebar">
    <div id="sidebar-collapse">
        <div class="admin-block d-flex">
            <div style="background-color: #ccc; padding: 7px; width: 40px; text-align: center; vertical-align: center; border-radius: 50%;">
                <i class="fa fa-user fa-2x"></i>
            </div>
            <div class="admin-info">
                <div class="font-strong">{{{ auth()->user()->name }}}</div><small>{{ auth()->user()->role }}</small></div>
        </div>
        <ul class="side-menu metismenu">
            <li>
                <a class="active" href="{{ route(auth()->user()->role) }}"><i class="sidebar-item-icon fa fa-th-large"></i>
                    <span class="nav-label">Dashboard</span>
                </a>
            </li>

            <li class="heading">FEATURES</li>

            <li>
                <a href=""><i class="sidebar-item-icon fa fa-images"></i>
                    <span class="nav-label">Slider Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('slider.create')}}">Add Slider</a>
                    </li>
                    <li>
                        <a href="{{ route('slider.index') }}">Slider List</a>
                    </li>
                </ul>
            </li>


            <li>
                <a href=""><i class="sidebar-item-icon fa fa-sitemap"></i>
                    <span class="nav-label">Category Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('category.create') }}">Menu Add</a>
                    </li>
                    <li>
                        <a href="{{ route('category.index') }}">Menu List</a>
                    </li>
                </ul>
            </li>

            <li>
                <a href=""><i class="sidebar-item-icon fa fa-shopping-bag"></i>
                    <span class="nav-label">Products Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('product.create') }}">Item Add</a>
                    </li>
                    <li>
                        <a href="{{ route('product.index') }}">Item List </a>
                    </li>
                </ul>
            </li>

            <li>
                <a href=""><i class="sidebar-item-icon fa fa-users"></i>
                    <span class="nav-label">Users Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('user.create') }}">User Add</a>
                    </li>
                    <li>
                        <a href="{{ route('user.index') }}">User List</a>
                    </li>
                </ul>
            </li>

        </ul>
    </div>
</nav>
<!-- END SIDEBAR-->

resources/views/admin/section/top-link.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content={{ csrf_token() }}>
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <title>@yield('title')</title>

    <link rel="stylesheet" href="{{ asset('css/admin.css') }}">

    @yield('styles')

</head>

<body class="fixed-navbar">