routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/****************** Route for front-end **********************/
Route::get('/products','ProductController@getAllProducts')->name('product-list');       //defined in cafe menu
Route::get('/products/featured','ProductController@getAllFeaturedProducts')->name('featured-products');
Route::get('/product/{slug}','ProductController@show')->name('product-detail');    //define in product-list   product's title
Route::get('/category/{slug}','CategoryController@getAllProductsByCategory')->name('category-products');    //defined in Helpers.php
Route::get('/category/{parent_slug}/{slug}','CategoryController@getAllProductsByChildCategory')->name('child-category-products');
Route::post('/product/{slug}','ProductController@submitReview')->name('product-review');
Route::get('/cart','CartController@showCart')->name('cart-list');
Route::get('/checkout','CartController@checkout')->name('checkout')->middleware(['auth','user']);
//route for cart
Route::post('/cart/add','CartController@addToCart')->name('add-to-cart');
Route::get('/loadmore', 'LoadMoreController@index');
Route::post('/loadmore/load_data', 'LoadMoreController@load_data')->name('loadmore.load_data');
Route::get('/esewa','CartController@esewa')->name('esewa');


/****************** Route for front-end **********************/



/****************** Route for user redirect on their dashboard **********************/

Route::group(['prefix'=>'admin','middleware'=>['auth','admin']],function (){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('slider','SliderController');
    Route::resource('category','CategoryController');
    Route::resource('product','ProductController');
    Route::resource('message','MessageController');
    Route::resource('user','UserController');
    Route::get('/change-pwd/{id}','UserController@changePassword')->name('user-change-pwd');
    Route::put('/change-pwd/{id}','UserController@submitChangePassword')->name('password-change');
});

//for show sub-category in the product-form
Route::post('/get-child','CategoryController@getChildByParent')->name('get-child')->middleware('auth');
//


Route::group(['prefix'=>'seller','middleware'=>['auth','seller']],function (){
    Route::get('/','HomeController@seller')->name('seller');

    Route::resource('products','SellerProductController');
});

Route::group(['prefix'=>'user','middleware'=>['auth','user']],function (){
    Route::get('/','HomeController@user')->name('user');
});

/****************** Route for user redirect on their dashboard **********************/






//Auth route for login and register

Route::get('/', 'FrontendController@index')->name('homepage');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Auth route for login and register

resources/views/seller/section/sidebar.blade.php
<!-- START SIDEBAR-->
<nav class="page-sidebar" id="sidebar">
    <div id="sidebar-collapse">
        <div class="admin-block d-flex">
            <div style="background-color: #ccc; padding: 7px; width: 40px; text-align: center; vertical-align: center; border-radius: 50%;">
                <i class="fa fa-user fa-2x"></i>
            </div>
            <div class="admin-info">
                <div class="font-strong">{{{ auth()->user()->name }}}</div><small>{{ auth()->user()->role }}</small></div>
        </div>
        <ul class="side-menu metismenu">
            <li>
                <a class="active" href="{{ route(auth()->user()->role) }}"><i class="sidebar-item-icon fa fa-th-large"></i>
                    <span class="nav-label">Dashboard</span>
                </a>
            </li>

            <li class="heading">FEATURES</li>

            
            <li>
                <a href=""><i class="sidebar-item-icon fa fa-shopping-bag"></i>
                    <span class="nav-label">Products Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('products.create') }}">Product Add</a>
                    </li>
                    <li>
                        <a href="{{ route('products.index') }}">Product List </a>
                    </li>
                </ul>
            </li>

            <li>
                <a href=""><i class="sidebar-item-icon fa fa-shopping-cart"></i>
                    <span class="nav-label">Order Manager</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="">Level 2</a>
                    </li>
                    <li>
                        <a href="">Level 3 </a>
                    </li>
                </ul>
            </li>

            
        </ul>
    </div>
</nav>
<!-- END SIDEBAR-->